# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-08 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('person', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('video_url', models.CharField(default=None, max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
