# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-31 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxsoundboard_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sound',
            options={'ordering': ('num_plays',)},
        ),
        migrations.AddField(
            model_name='sound',
            name='num_plays',
            field=models.IntegerField(default=0),
        ),
    ]
