# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-19 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxsoundboard_project', '0002_auto_20171231_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sound',
            options={'ordering': ('-num_plays',)},
        ),
        migrations.AddField(
            model_name='sound',
            name='rank',
            field=models.BooleanField(default=True),
        ),
    ]
